[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project.urls]
"Homepage" = "https://github.com/momijiame/shirokumas"

[project]
name = "shirokumas"
description = "A set of scikit-learn style transformers for Polars"
readme = "README.md"
license = {file = "LICENSE"}
requires-python = ">=3.11"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "polars>=1.36.0",
    "scikit-learn",
    "scipy",
]
dynamic = ["version"]

[project.optional-dependencies]
dev = [
    "pytest",
    "ruff",
    "mypy",
    "pylint",
    "build",
    "twine",
    "sphinx-rtd-theme",
    "sphinx-autobuild",
]

[tool.setuptools_scm]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
preview = true
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # Pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "UP",  # pyupgrade
    "RUF",  # Ruff-specific rules
    "PIE",  # flake8-pie
    "PERF",  # Perflint
    "FURB",  # refurb
    "LOG",  # flake8-logging
    "G",  # flake8-logging-format
    "T20",  # flake8-print
    "FA",  # flake8-future-annotations
    "YTT",  # flake8-2020
    "INT",  # flake8-gettext
    "SLOT",  # flake8-slots
    "PLE",  # Pylint errors
    "PLW",  # Pylint warnings
]

[tool.ruff.lint.isort]
force-single-line = true

[tool.mypy]
no_strict_optional = true
ignore_missing_imports = true
check_untyped_defs = true

[tool.pylint]
disable = "C,R"
